---
sidebarDepth: 0
---

# 错误信息收集

[[toc]]

## try catch 方案

try catch 处理异常的能力有限，对于运行时非异步错误，它并没有问题。但是对于：`语法错误`、`异步错误`，try catch 就无法 cover 了。

```js
// 以下错误无法捕获
try {
  var a =\ 'a'
} catch(e) {
  console.log(e);
}

try {
  setTimeout(() => {
    a
  })
} catch(e) {
console.log(e)
}
```

**try catch 能力有限，且对于代码的侵入性较强。**

## window.onerror

开发者只需要给 window 添加 onerror 事件监听，**同时注意需要将 window.onerror 放在所有脚本之前，这样才能对语法异常和运行异常进行处理。**

```js
window.onerror = function(message, source, lineno, colno, error) {
  // ...
};
```

- message：错误信息（字符串）。可用于 HTML onerror=""处理程序中的 event。
- source：发生错误的脚本 URL（字符串）
- lineno：发生错误的行号（数字）
- colno：发生错误的列号（数字）
- error：为错误的对象信息，比如 error.stack 获取错误的堆栈信息。

window.onerror 这种方式对代码侵入性较小，也就不必涉及 AST 自动插入脚本。除了对语法错误和网络错误（**因为网络请求异常不会事件冒泡**）无能为力以外，无论是异步还是非异步，onerror 都能捕获到运行时错误。

## 对 Promise 错误处理

我们都提倡养成写 Promise 的时候最后写上 catch 函数的习惯。ESLint 插件 eslint-plugin-promise 会帮我们完成这项工作，使用规则：catch-or-return 来保障代码中所有的 promise（被显式返回的除外）都有相应的 catch 处理。

```js
new Promise((resolve, reject) => {
  resolve();
})
  .then(
    () => {
      throw new Error();
      console.log('resolved');
    },
    (err) => {
      console.log('rejected');
      throw err;
    }
  )
  .catch((err) => {
    console.log(err, 'catch');
  });
```

onRejected 并不能捕获 then 方法中第一个参数 onResolved 函数中的错误。

对于 Promise 的错误处理，我们还可以注册对 Promise 全局异常的捕获事件 unhandledrejection：

```js
window.addEventListener('unhandledrejection', (e) => {
  e.preventDefault();
  console.log(e.reason);
  return true;
});
```

这对于集中管理和错误收集更加友好。

## 处理网络加载错误

用 script 标签，link 标签进行脚本或者其他资源加载时，由于某种原因（可能是服务器错误，也可能是网络不稳定），导致了脚本请求失败，网络加载错误。

可以使用 window.addEventListener('error') 方式对加载异常进行处理，注意这时候我们无法使用 **window.onerror 进行处理，因为 window.onerror 事件是通过事件冒泡获取 error 信息的，而网络加载错误是不会进行事件冒泡的。**

::: tip

这里多提一下，不支持冒泡的事件还有：鼠标聚焦 / 失焦（focus / blur）、鼠标移动相关事件（mouseleave / mouseenter）、一些 UI 事件（如 scroll、resize 等）。

::::

window.addEventListener 不同于 window.onerror，它通过事件捕获获取 error 信息，从而可以对网络资源的加载异常进行处理：

```js
window.addEventListener(
  'error',
  (error) => {
    console.log(error);
  },
  true
);
```

怎么区分网络资源加载错误和其他一般错误呢？这里有个小技巧，普通错误的 error 对象中会有一个 `error.message` 属性，表示错误信息，而资源加载错误对应的 error 对象却没有，因此可以根据下面代码进行判断：

```js
window.addEventListener(
  'error',
  (error) => {
    if (!error.message) {
      // 网络资源加载错误
      console.log(error);
    }
  },
  true
);
```

因为没有 error.message 属性，我们也就没有额外信息获取具体加载的错误细节，现阶段也无法具体区分加载的错误类别：比如是 404 资源不存在还是服务端错误等，只能配合后端日志进行排查。

## 页面崩溃收集和处理

一个成熟的系统还需要收集崩溃和卡顿，对此我们可以监听 window 对象的 load 和 beforeunload 事件，并结合 sessionStorage 对网页崩溃实施监控：

```js
window.addEventListener('load', () => {
  sessionStorage.setItem('good_exit', 'pending');
});

window.addEventListener('beforeunload', () => {
  sessionStorage.setItem('good_exit', 'true');
});

if (sessionStorage.getItem('good_exit') && sessionStorage.getItem('good_exit') !== 'true') {
  // 捕获到页面崩溃
}
```

## 框架的错误处理

react 16 之后的版本，使用著名的 `componentDidCatch` 来处理错误。

Vue 中的错误捕获机制

```js
Vue.config.errorHandler = function(err, vm, info) {
  let {
    message, // 异常信息
    name, // 异常名称
    stack, // 异常堆栈信息
  } = err;
  // vm 为抛出异常的 Vue 实例
  // info 为 Vue 特定的错误信息，比如错误所在的生命周期钩子
};
```

## 参考资料

- [前端开发核心知识进阶：50 讲从夯实基础到突破瓶颈](https://www.zhihu.com/market/paid_column/1167078439772721152/section/1169977684410564608)
